config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  delete "/relationships", to: "relationships#destroy"


  root to: "posts#index"
  
  resources :users
  resources :posts, except: :index
  resources :sessions, only: [:new, :destroy, :create]
  resources :relationships, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image,
              styles: {thumbnail: "60x60", large: "300x300"}
  validates :user_id, presence: true
  validates :description, length: {maximum: 255}
  validates_attachment :image, presence: true, content_type: {content_type: ["image/png", "image/jpeg"]},  size: {in: 1..5000.kilobytes}

  belongs_to :user, dependent: :destroy

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates_presence_of :follower_id, :followed_id
  # validates_numericality_of :follower_id, :followed_id
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  before_create :create_remember_token
  has_secure_password
  has_many :posts
  has_many	:relationships,	foreign_key:	"follower_id",	dependent:	:destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
            dependent: :destroy, class_name: "Relationship"
  has_many :followers, through: :reverse_relationships



  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :login, presence: true, uniqueness: true,
                    length: {minimum: 3, maximum: 12}
  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    format: VALID_EMAIL_REGEX
  validates :password, length: {minimum: 6}


  def	User.new_remember_token
      SecureRandom.urlsafe_base64
  end

  def	User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
  end

  def follow(user)
    self.relationships.create(followed_id: user)
  end

  def unfollow(user)
    self.relationships.find_by_followed_id(user).destroy if following?(user)
  end

  def following?(user)
      self.relationships.find_by_followed_id(user)
  end

  def feed
    Post.where(user_id: followed_user_ids)
  end

  private
  def	create_remember_token
      self.remember_token	=	User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_signed_in, except: :show
  before_action :set_post, only: [:show, :destroy, :edit, :update]


  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def edit
    
  end
  
  def update
    if @post.update(article_params)
        flash[:notice] = "Successfully updated post!"
        redirect_to @post
      else
        flash[:alert] = "Error updating post!"
        render 'edit'
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:image, :description)
  end

  def check_signed_in
    redirect_to signin_path unless signed_in?
  end
  
  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    current_user.unfollow(params[:user_id])
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.js {}
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end

  def create
    user = User.find_by_login(params[:session][:login])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash[:danger] = "Invalid login or password"
      render "new"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @posts = current_user.feed
      @user = current_user
    else
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :destroy, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @posts = @user.posts
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to @user
    else
      render "edit"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :password, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    " | " + title unless title.empty?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token	=	User.new_remember_token
		cookies.permanent[:remember_token]	=	remember_token
		user.update_attribute(:remember_token,	User.encrypt(remember_token))
		self.current_user	=	user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
    User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def	current_user=(user)
			@current_user	=	user
	end
	
  def current_user
    remember_token	=	User.encrypt(cookies[:remember_token])
    @current_user ||=
    User.find_by_remember_token(remember_token)
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user?(user)
    return user == @current_user
  end
  
  def current_user_id
    return @current_user
  end
  
 

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram <%= full_title(yield :title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/header" %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="panel panel-<%= key %>">
          <div class="panel-heading">
            <%= value %>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_follow.html.erb
<%= link_to "Follow", relationships_path(user_id: params[:id]), method: :post, remote: true, class: "btn btn-large btn-primary" %>

app/views/partials/_follow_status.html.erb
<% if current_user.following?(params[:id]) %>
  <%= render "partials/unfollow" %>
<% else %>
  <%= render "partials/follow" %>
<% end %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Instagram</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'Explore', users_path %></li>
          <li><%= link_to 'My Account', user_path(current_user)  %></li>
          <li><%= link_to 'Logout', signout_path, method: :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', signin_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_unfollow.html.erb
<%= link_to "Unfollow", relationships_path(user_id: params[:id]), method: :delete, remote: true, class: "btn btn-large btn-default" %>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <%= f.text_field :description, placeholder: "description" %>
  <%= f.file_field :image %>
  <%= f.submit "Post"%>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<%= image_tag @post.image(:large) %>
<h3><%= @post.description %></h3>

app/views/relationships/create.js.erb
$(".follow_status").html("<%= escape_javascript(render('partials/unfollow')) %>");

app/views/relationships/destroy.js.erb
$(".follow_status").html("<%= escape_javascript(render('partials/follow')) %>");

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>

<div class="container">
<div class="col-md-8 col-md-offset-2">
      <% if signed_in? %>
      
          <% @posts.each do |post| %>
          
            <div class="feed-post">
            <a href="/users/<%= post.user_id %>"><%= image_tag post.user.avatar , class:"feed-avatar" %><%= post.user.login %></a>  
            
            <%= image_tag post.image, class:"img-responsive feed-img" %>
            <p><%= post.description %></p>
            </div>
      <% end %> 
</div>
  <% else %>
    <%= render "sessions/form" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <ul>
  <% @user.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.text_field :login, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.text_field :email, class:"form-control" %>
</div>

<div class="form-group">
  <%= f.file_field :avatar, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.password_field :password, class: "form-control" %>
</div>
  <%= f.submit "Edit" %>
<% end %>

app/views/users/index.html.erb
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
         <%= image_tag user.avatar.url(:thumb),  class: "img-circle" %>
         <%= link_to user.login, user %>
         <button class="btn btn-primary follow">Follow</button>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul>
  <% @user.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
  <%= f.text_field :login, class="form-control" %>
    </div>
    <div class="form-group">
  <%= f.text_field :email , class="form-control"%>
    </div>
    <div class="form-group">
  <%= f.password_field :password , class="form-control"%>
    </div>
    <div class="form-group">
  <%= f.file_field :avatar, class="form-control" %>
  </div>
  <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.login %></h2>
<%= image_tag @user.avatar.url(:thumb), class:"img-circle" %>
<% if current_user? @user %>
  <%= link_to 'Edit Profile', edit_user_path(current_user) %>
  <%= @user.followers.count %>
<% else %>
  <div class="follow_status">
    <%= render "partials/follow_status" %>
  </div>
<% end %>
<div class="container">
  <% @posts.in_groups_of(3, false).each do |group| %>
    <div class="row">
        <% group.each do |post| %>
          <div class="col">
            <%= image_tag post.image, class:"post_image" %>
            <div class="overlay">
              <p><%= post.description %></p>
            </div>
            </div>
        <% end %>
    </div>
  <% end %>
</div>